// State tests for the bundled interface; not a browser layout/device test.
const test=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
function setup(persisted={}){
 const html=fs.readFileSync(path.join(__dirname,'../app/src/main/assets/index.html'),'utf8');
 const elements=new Map();let pending=[];
 function el(){const classes=new Set();return {textContent:'',value:'',style:{setProperty(){}},attrs:{},disabled:false,children:[],classList:{toggle(k,force){const enabled=force===undefined?!classes.has(k):force;enabled?classes.add(k):classes.delete(k);return enabled},contains:k=>classes.has(k)},setAttribute(k,v){this.attrs[k]=String(v)},append(...nodes){this.children.push(...nodes)},replaceChildren(){this.children=[]},showModal(){this.open=true},close(){this.open=false}}}
 const get=id=>{if(!elements.has(id))elements.set(id,el());return elements.get(id)};
 const modes=[el(),el(),el()];const body=el();const doc={getElementById:get,body,documentElement:el(),querySelectorAll:()=>modes,createElement:el,addEventListener(){}};
 const storage=new Map(Object.entries(persisted));
 const context=vm.createContext({localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},document:doc,window:{},URL,Date,alert(){},setInterval:()=>1,clearInterval(){},setTimeout:fn=>{pending.push(fn);return pending.length},clearTimeout:()=>{pending=[]}});
 vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);
 return {get,context,body,storage,next:()=>pending.shift()?.()};
}
test('demo is labelled, completes segments, and stops without microphone',()=>{const s=setup();s.get('demo').onclick();assert.match(s.get('status').textContent,/توضيحي/);assert.equal(s.get('demo').disabled,true);s.next();s.get('history').onclick();assert.equal(s.get('historyList').children.length,1);assert.match(s.get('historyList').children[0].children[0].textContent,/تجريبي/);s.get('start').onclick();assert.equal(s.get('demo').disabled,false)});
test('font bounds, mosque mode and dark mode work',()=>{const s=setup();for(let i=0;i<30;i++)s.get('larger').onclick();assert.equal(s.get('sizeLabel').textContent,60);assert.equal(s.get('larger').disabled,true);for(let i=0;i<30;i++)s.get('smaller').onclick();assert.equal(s.get('sizeLabel').textContent,26);s.get('focus').onclick();assert.equal(s.body.classList.contains('focus'),true);s.get('theme').onclick();assert.equal(s.body.classList.contains('dark'),true)});
test('preview never claims to translate real audio; cloud event updates safe text',()=>{const s=setup();s.get('start').onclick();assert.match(s.get('message').textContent,/معاينة/);s.context.window.bayanEvent('caption',{ar:'<script>untrusted</script>',ur:'اردو متن',final:true});assert.equal(s.get('arabic').textContent,'<script>untrusted</script>');assert.equal(s.get('urdu').textContent,'اردو متن');s.context.window.bayanEvent('error',{message:'network unavailable'});assert.equal(s.get('demo').disabled,false);assert.equal(s.get('message').textContent,'network unavailable')});

test('restores reading preferences and excludes credentials from saved settings',()=>{const s=setup({'bayan-preferences':JSON.stringify({fontSize:48,dark:true,locale:'ar-QA',endpoint:'https://example.com/token'})});assert.equal(s.get('sizeLabel').textContent,48);assert.equal(s.body.classList.contains('dark'),true);assert.equal(s.get('locale').value,'ar-QA');s.get('access').value='secret-do-not-save';s.get('larger').onclick();const saved=JSON.parse(s.storage.get('bayan-preferences'));assert.equal(saved.fontSize,50);assert.equal(saved.endpoint,'https://example.com/token');assert.equal('access' in saved,false);assert.equal(JSON.stringify(saved).includes('secret-do-not-save'),false)});
